### ISSUE TITLE
get_news(): encoding.

### ISSUE THREAD

**Issue by MikeJohnPage** [datakolektiv/newsrivr#13]
Currently, data that is parsed from the json Newsriver is UTF-8 encoded (fairly standard):
```r
    # Return error if there is a http error, else parse the content from the
    # json file and store the title, text, date, and website in a tibble
    if (httr::http_error(resp) == TRUE) {
      warning("The request failed")
    } else {
      news_tbl <- jsonlite::fromJSON(httr::content(resp,
        as = "text",
        encoding = "UTF-8"
      ),
      flatten = TRUE
      )

      news_tbl <- tibble::as_tibble(news_tbl)

      return(news_tbl)
    }
```
Concerns:
- Will this encoding standard potentially throw an error to a user? 
- Will valuable information be lost?
- Should the `encoding = "UTF-8"` argument be removed all together and any encoding tasks passed onto the `clean_news()` function? See below for more info.

**Comment by MikeJohnPage** [comment]
- read iconf
- if you find garbage in a document, consider discarding it
- place encoding tasks into `clean_news()` not `get_news()`

**Comment by MikeJohnPage** [comment]
The current solution is that ` encoding = "UTF-8"` has been removed so the default `encoding = NULL` behavior is invoked. Encoding responsibilities have been passed to `clean_news()` in which a sensible UTF-8 encoding default has been invoked using base R `enc2utf8`.

**Comment by MikeJohnPage** [comment]
The encoding returned by the Newsriver API needs investigating, it may be that the characters are UTF-8 encoded by default (rendering all these steps redundant).

**Comment by MikeJohnPage** [comment]
UTF-8 is almost a universal standard. Should UTF-8 encoding be forced as a default to save the cognitive overhead with trying to resolve this solution?

**Comment by GoranMilovanovic** [comment]
Sincerely: I always enforce to UTF-8.

**Comment by MikeJohnPage** [comment]
Newsriver enforces UTF-8 by default.
