### ISSUE TITLE
store_creds_temp(): Sys.setenv behaviour

### ISSUE THREAD

**Issue by MikeJohnPage** [datakolektiv/newsrivr#18]
As it stands `store_creds_temp()` makes use of `Sys.setenv()` to temporarily store user credentials for the session:

```r
store_creds_temp <- function() {
  Sys.setenv(
    NEWSRIVER_API_KEY = askpass::askpass("Please enter API key"),
    NEWSRIVER_USER_AGENT = askpass::askpass("Please enter user agent")
  )

  # send success message
  message <- paste("Your credentials have been successfully stored for the current session",
    sep = "\n"
  )
  message(message)
}
```

This is the desired behaviour. However, having read through the package documentation, I am uncertain as to how exactly `Sys.setenv()` works. Is is the case that `Sys.setenv()` will always only store the user credentials for just that session (if not called though a global environment variable such as `.Renviron`?

Experiment with different R sessions and projects confirms this to be the case, but a more firm answer is required. We don't want to invoke any unexpected changes and behaviour to global variables.

**Comment by GoranMilovanovic** [comment]
Generally, it is advised not to mess up with global variables from packages at all.

I think {TwitteR}, for example, does not go for that: an example of a well-know package that also wraps up an API and asks for user credentials. Perhaps go and take a look at the way they have solved the issue there?

**Comment by MikeJohnPage** [comment]
I disagree. Starting with three examples:

- {twitteR} has been [depreciated](https://github.com/geoffjentry/twitteR) in favour of {rtweet} for some time. {rtweet} clearly states in the [tokens.R](https://github.com/mkearney/rtweet/blob/master/R/tokens.R) documentation that "users should save the path to token(s) as an environment variable".
- A similar news API wrapper package, [{newsanchor}](https://github.com/CorrelAid/newsanchor) stores API tokens to the `.Renviron` variable.
- The {httr} managing secrets vignette contains a section advocating the storage of API tokens in the `.Renviron` file.

Writing API tokens in a file or in the console is bad practice, as credentials can easily be leaked either in the file directly, or in `.Rhistory`.

As `store_creds()` is optional (i.e., users have to opt in to calling the function), global variables will not be changed without users direct approval (not to mention that storing an API key in the `.Renviron` file will likely cause absolutely zero problems for users given its advocation by prominent packages and developers).

`store_creds_temp()` provides a backup function if users are still not happy editing their `.Renviron` variable.

**Comment by GoranMilovanovic** [comment]
Mike, in that case: go for storing the credentials as an environment variable.
I can only say that you have obviously studied this problem thoroughly.

**Comment by MikeJohnPage** [comment]
As a happy middle ground, I've now added `api_token` and `ua` arguments to `get_news()`. The function now works so it defaults to reading the users api token and user agent by default from the `.Renviron` file, however, users can now also just declare them in the function argument should they choose (however, this behaviour will be discouraged in the vignette for security reasons):

```r
get_news(query = "Google", api_token = "myfakeapitoken", ua = "myfakeemail@email.com")
```
