### ISSUE TITLE
get_news(): return json

### ISSUE THREAD

**Issue by MikeJohnPage** [datakolektiv/newsrivr#2]
Add argument to `get_news()` that when passed returns the data as a json.

Perhaps a separate function is needed as `get_news()` currently calls `purrr::map_dfr()` to combine tibbles.

**Comment by MikeJohnPage** [comment]
I am starting to think we should have a change of strategy. The `get_news()` function is becoming flooded with arguments. Not only does this complexity create space for bugs, but will also make the UX poor.

Accordingly, let's split `get_news()` into two functions, each declaring the returned data type:

- `get_news_tibble()` **or** `get_news()`
- `get_news_json()`

The functions will be near identical accept for their return type. This thinking is roughly alligned with the {purrr} `map` functions that allow you to explicitly declare the return type (e.g., `map_dbl`).

**Comment by MikeJohnPage** [comment]
get_news (or whatever it will be called) will be passable in to `clean_news()` where as `get_news_json` won't. Is this an issue from a UX perspective (I think not).

On second thoughts, I think `get_news()` should be the function name that returns the tibble (as this will be the majority use case), and it integrates nicely with the name `clean_news()`. `get_news_json()` can be declared as separate from the main workflow to make the UX clear.

**Comment by GoranMilovanovic** [comment]
Why do we need a function that returns `json` at all?

Example: R packages used to fetch Wikipedia/Wikidata return R data types, not `json` (which is one option when you use the API directly, second being XML, etc).

Returning tibbles only sounds perfect to me.

**Comment by MikeJohnPage** [comment]
Agreed.
