### ISSUE TITLE
get_news(): Boolean operators

### ISSUE THREAD

**Issue by MikeJohnPage** [datakolektiv/newsrivr#6]
The Newsriver API can accept an infinite number of search terms into the text and title query parameters, split by Boolean operators (I have emailed the author for clarification and will update this issue if it does not hold true).

Currently, `get_news` limits the scope to how we define the `query_params` (containing the number of search terms and Boolean operators) which is currently set to:
```
  # Set query parameters to be called
  query_params <- sprintf(
    stringr::str_c(
      'title:("',
      search_term_higher,
      '" OR "',
      search_term_lower,
      '") AND text:("',
      search_term_higher,
      '" OR "',
      search_term_lower,
      '") AND language:en AND discoverDate:[%s TO %s]'
    ),
    search_dates,
    search_dates + 1
  )
```
It was set this way as the function was only initially required to retrieve articles containing two search terms (one being the capitalised version of the other).

How can we create an argument to `get_news` that allows any number of search terms (and consequently Boolean operators) to be used?

**Comment by GoranMilovanovic** [comment]
First, why the increased code complexity with `sprintf`?
Second, the answer to your question: you need to use something from the `apply()` family (I would say `sapply` or `lapply` would do) to wrap-up the generation of search strings so that the API syntax for many search terms is generated. That should not be too difficult.

**Comment by MikeJohnPage** [comment]
- Try `paste0`instead of sprintf
- Try map/reduce to paste together n search terms
