### ISSUE TITLE
get_news(): query params

### ISSUE THREAD

**Issue by MikeJohnPage** [datakolektiv/newsrivr#7]
Each query parameter specified at the top of [functions.Rmd](https://github.com/datakolektiv/newsrivr/blob/master/functions.Rmd) needs iteratively adding as an argument to `get_news()`. Please tick as each is completed:

 __query__  
  - [x] title 
  - [x] text  
  - [x] discoverDate  
  - [x] language  
  - [ ] url  
  - [ ] website.domainName  
  - [x] metadata.readTime  
  - [x] website.countryCode  
  - [x] elements.type   

 __sortBy__   
  - [x] score  
  - [x] discoverDate  
  - [x] metadata.readTime.seconds   

 __sortOrder__   
  - [x] ASC  
  - [x] DESC   

 __limit__   
  - [x] 1:100

**Comment by MikeJohnPage** [comment]
I am in a dialogue with Elia over at Newsriver and he said:

> I am currently considering to limit the query to 500 chars

The above query params needs designing in line with these limits. Will update once confirmed.

**Comment by MikeJohnPage** [comment]
Confirmed. The _query_ variable from the list of query parameters (_query_, _sortBy_, _sortOrder_, _limit_) will be limited in the future to 500 chars.

For example in the follow GET request to the API:

```
"https://api.newsriver.io/v2/search?query=title%3AGoogle%20AND%20text%3Adata%20AND%20text%3Aprivacy&sortBy=_score&sortOrder=DESC&limit=15
```

the section `title%3AGoogle%20AND%20text%3Adata%20AND%20text%3Aprivacy` will be the limited section.

**Comment by MikeJohnPage** [comment]
A plan for **sortBy**, **sortOrder**, and **limit** has been establish. The remaining piece of the puzzle is supplying a simple to use query argument to `get_news()`.

**Comment by MikeJohnPage** [comment]
For `discoverDate` have a `search_date_by` arg, or something to that nature, that allows users to search by either day or month. Write conditional checks to make sure arguments are matched and errors aren't thrown.

**Comment by MikeJohnPage** [comment]
Currently, arguments `sortBy` and `sortOrder` will **not** be inputs to the `get_news()` function These arguments will be preset by newsrivr (current defaults are `_score` and `DESC` respectively). Sorting of results can be passed either to `clean_news()` or taken care of by the user.

If in the future we want to add `sortOrder` and `sortBy` as args, then they can be added like so:

```r
get_news(sortOrder = c("_score", "discoverDate", metadata.readTime.seconds), sortBy = c("ASC", DESC"), ...)
```
To do so would require the use of [`match.arg`](https://www.math.ucla.edu/~anderson/rw1001/library/base/html/match.arg.html). For an example see [here](https://github.com/tidyverse/tidyr/blob/master/R/fill.R).

**Comment by MikeJohnPage** [comment]
Keywords matches in the `title` and `text` are going to be taken care of by one argument: `query`.

As the `title` and `text` fields can take any combination of keyword/phrases separated by Boolean operators, it is going to be difficult to code. An easier solution is to write a clear vignette demonstrating how to write Newsriver valid queries (which take Lucene query strings). It is as simple as separating keywords or phrases by AND/OR/NOT operators, and indicating whether to search by `text` or `title`. For example:

```r
get_news(query = "text:(Barack AND Obama)")
```
or
```r
get_news(query = "title:("Microsoft" OR "Google")")
```
etc.

**Note:** a quick and dirty solution for using `get_news()` still exists implementing this strategy: Users can specify a keyword or phrase to search by without worrying about generating custom Newsriver valid queries. For example:

```r
get_news(query = "Google", from = "2019... etc.)
```
will still search Newsriver for articles containing the keyword "Google". It just won't be specific to the title or text fields.

**Comment by MikeJohnPage** [comment]
In fact, the above solution creates the issue that generated queries will either need to escape double quotes, or single quotes will have to be used:
```r
get_news(query = 'text:"Google" AND title:"Google"', from = "2019-01-01", to = "2019-01-03")
```

Accordingly - it needs ascertaining whether single and double quotes are encoded differently when {httr} make a call to Newsriver, and whether Newsriver treats them differently.

**Comment by MikeJohnPage** [comment]
When `query = 'text:("Google" OR "Apple") AND title:"Google"'` the API call (determined by the response object) is encoded as:
```
Response [https://api.newsriver.io/v2/search?query=%22text%3A%28%22Google%22%20OR%20%22Apple%22%29%20AND%20title%3A%22Google%22%22%20AND%20language%3Aen%20AND%20discoverDate%3A%5B2019-01-01%20TO%202019-01-02%5D&sortBy=_score&sortOrder=DESC&limit=100]
```

When `query = "text:('Google' OR 'Apple') AND title:'Google'"` the API call (determined by the response object) is encoded as:

```
Response [https://api.newsriver.io/v2/search?query=%22text%3A%28%27Google%27%20OR%20%27Apple%27%29%20AND%20title%3A%27Google%27%22%20AND%20language%3Aen%20AND%20discoverDate%3A%5B2019-01-01%20TO%202019-01-02%5D&sortBy=_score&sortOrder=DESC&limit=100]
```
As can be seen above, double quotes are encoded as `%22` and single quotes as `%27` as would be [expected](https://www.w3schools.com/tags/ref_urlencode.asp).

**Comment by GoranMilovanovic** [comment]
Two things:

1. I am not sure if I understand your dilemma in relation to the previous comment: it seems that everything works fine with `httr`, right? Let me know if I am missing something please. 

2. Your observation in [this comment](https://github.com/datakolektiv/newsrivr/issues/7#issuecomment-499628130): "... a quick and dirty solution for using get_news() still exists implementing this strategy..." - be aware that most of the users, most probably, will want to use the package in exactly the "quick and dirty" way that you have described.

**Comment by MikeJohnPage** [comment]
The issue is not with `httr`, which is working fine, the issue is that the same queries, encoded differently, return different results. Having read the documentation on the Newsriver site, I think double quotes are the only valid form for Lucene query syntax (which is the method used to generate queries on Newsriver). Thus if users want to generate custom queries beyond a single keyword search, they need to use this form when calling `get_news()`:
```r
get_news(query = 'text:"Google" AND title:"Google"', ...)
```
Calling arguments with single quotes is unusal behaviour for most R users, and may be a source of 
error, but I think the only way to take of this is to use clear documentation with examples.

I agree most users will want the quick solution. Fortunately, the current implementation allows users to do this, using standard double quotes. For example:

```r
get_news(query = "Apple iPad", ...)
```
is perfectly valid.

**Comment by GoranMilovanovic** [comment]
How about writing out a regex that would fix the queries so to match the Lucene syntax conventions?
I do not know the conventions, however, if the problem is to make the query encompassed in single quotes, while everything inside the query is double quoted... regex.

**Comment by GoranMilovanovic** [comment]
Let me know if my line of thinking falls anything close to the problem, and if you need any help in writing out the regex expression for this.

**Comment by MikeJohnPage** [comment]
The official Lucene query synax documentation can be viewed [here](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html).

I don't understand how regex would fix the problem (_making the query encompassed in single quotes, while everything inside the query is double quoted_). Can you provide an example?

**Comment by GoranMilovanovic** [comment]
Not now - I am on the Notebooks, and I certainly do not have the time to learn Lucene syntax at this point.

However, *if* the problem is only to make the query (a) begin with single quotes, (b) end with single quotes, and (c) use nothing but double quotes to encompass strings in the query, then [regex](https://stat.ethz.ch/R-manual/R-devel/library/base/html/regex.html) can certainly fix it.

**Comment by MikeJohnPage** [comment]
Fine. To be sorted at a later date. For now double quotes work for single search terms. It is only when users require phrases that this becomes an issue. 

Clear documentation will suffice for now.

**Comment by MikeJohnPage** [comment]
> Currently, arguments `sortBy` and `sortOrder` will **not** be inputs to the `get_news()` function These arguments will be preset by newsrivr (current defaults are `_score` and `DESC` respectively). Sorting of results can be passed either to `clean_news()` or taken care of by the user.
> 
> If in the future we want to add `sortOrder` and `sortBy` as args, then they can be added like so:
> 
> ```r
> get_news(sortOrder = c("_score", "discoverDate", metadata.readTime.seconds), sortBy = c("ASC", DESC"), ...)
> ```
> 
> To do so would require the use of [`match.arg`](https://www.math.ucla.edu/~anderson/rw1001/library/base/html/match.arg.html). For an example see [here](https://github.com/tidyverse/tidyr/blob/master/R/fill.R).

Another good [solution](https://github.com/CorrelAid/newsanchor/blob/master/R/get_everything.R) exists in the newsanchor package. Check out their `sort_by` arg.

**Comment by MikeJohnPage** [comment]
> Confirmed. The _query_ variable from the list of query parameters (_query_, _sortBy_, _sortOrder_, _limit_) will be limited in the future to 500 chars.
> 
> For example in the follow GET request to the API:
> 
> ```
> "https://api.newsriver.io/v2/search?query=title%3AGoogle%20AND%20text%3Adata%20AND%20text%3Aprivacy&sortBy=_score&sortOrder=DESC&limit=15
> ```
> 
> the section `title%3AGoogle%20AND%20text%3Adata%20AND%20text%3Aprivacy` will be the limited section.

I am placing this here for future reference. As noted above the query section of the GET request is restricted to 500 characters. This section is anything that falls after `"https://api.newsriver.io/v2/search?query=` and before `&sortBy=_score&sortOrder=DESC&limit=15`. Accordingly, regardless of the `query` called there will always be a standardised 86 common characters used in setting the language and search dates etc. that fall within this 500 character query limit:
```r
nchar("%22%22%20AND%20language%3Aen%20AND%20discoverDate%3A%5B2019-01-01%20TO%202019-01-02%5D")
#> [1] 86
```
Note the query will always fall between `%22` and `%22`. Therefore the **encoded** query passed by the user cannot exceed 414 characters (500-86).

**Comment by MikeJohnPage** [comment]
The main `search_tweets()` function from the {rtweet} package also accepts custom queries and has the same double quote issues we face. They simple just instruct the user to either escape `""` with a `\` or to wrap phrases in single quotes:

https://rtweet.info/reference/search_tweets.html
