### ISSUE TITLE
Function dependencies

### ISSUE THREAD

**Issue by MikeJohnPage** [datakolektiv/newsrivr#8]
Each function needs to be checked for its dependencies, and a decision made as to whether it should be kept or rewritten in base R (or a faster package).

Questions:

- If {package} is used in one function, does it make sense to try and remove it as a dependency from another function? Is it not true that it will be loaded into the namespace as {newsrivr} is loaded?
- Should all functions be rewritten using {data.table} and run in parallel using {snow} to maximise performance?

**Comment by GoranMilovanovic** [comment]
Q: If {package} is used in one function, does it make sense to try and remove it as a dependency from another function? Is it not true that it will be loaded into the namespace as {newsrivr} is loaded?

Use the DESCRIPTION file of your package for all the dependencies. Thus everything that you need will be loaded (and installed together w. {newsrivr} if necessary).

Q: Should all functions be rewritten using {data.table} and run in parallel using {snow} to maximise performance?

Well, using {data.table} will help with really large data sets only... you need to estimate if it is necessary to use it or not. As of {snow}: I would not go for running API calls in parallel. Also, I would use {snowfall} - a nice wrapper around a bit more complicated {snow}. You can take a look at my code in the lda_meta_features repository for examples of running topic models in parallel from {snowfall}, it is really easy.
